version : "3"
services:
  flaskapp:
    build:
      context: "./app"
      dockerfile: "dockerfile_1"
    image: "flaskimage:latest"
    ports:
      - "33790:80"
    depends_on:
      - "redis-server"
    restart: "on-failure"
    environment:
      mavariable: "Marie"
  redis-server:
    image: "redis:latest"
    restart: "on-failure"
    volumes:
      - mydata:/data
volumes:
  mydata: